### DISCUSSION TITLE
讨论：venus-market组件方案设计/升级改造

### DISCUSSION THREAD

**Discussion by Fatman13** [filecoin-project/venus#4750] [Ideas]
原文 by @hunjixin 

# market初始化用法简化讨论

## market 用法

支持场景

venus-market:

1. 共享部署  全部使用共享组件
   目前初始化命令行
   ```
   ./venus-market pool-run 
   --node-url <node url>                必须
   --messager-url <messager url>        必须 
   --auth-url <auth url>                必须
   --node-token <node token>            非必须   考虑删除
   --messager-token <messager token>    非必须   考虑删除
   --auth-token <auth token>            非必须   此处逻辑是如果没有单独设置node-token/messager-token时候，直接使用auth-token的token

   --piecestorage fs:/xx                必须
   --payment-addr <addr:account>        必须

   --signer-type gateway                考虑删除
   --signer-url <signer url>            必须
   --signer-token                       非必须   考虑删除
   ```

    这里的优化在于，
    1. 去除signer-type/signer-url，改为gateway-url, pool池化部署的方式下，不存在连接本地钱包的模式，也不存在之直连节点的情况，因而此处可以直接默认签名类型为gateway模式，其他的依旧保留。
    2. 隐藏node-token/messager-token/signer-token. signer-url重命名为gateway-url

2. 私有部署  

   1. 是否支持消息推送到messager                    
   2. 是否可以使用节点的签名
  
```
    ./venus-market solo-run 
    --node-url <node url>                   必须
    --node-token <node token>               非必须   考虑删除
    --messager-url                          考虑增加
    --messager-token <auth token>           非必须   考虑不使用
    --signer-type wallet                    目前可以 1. 不写则默认使用节点的签名  2. 默认使用本地钱包签名
    --signer-url <local wallet url>         不写或者使用钱包
    --signer-token <local wallet token>     钱包模式必须/直连情况不需要配置

    --piecestorage fs:/xx --miner <f0xxx>   必须
    --payment-addr <addr:account>           必须
```

```toml
# Default config:
HomeDir = "~/.venusmarket"
ConsiderOnlineStorageDeals = true
ConsiderOfflineStorageDeals = true
ConsiderOnlineRetrievalDeals = true
ConsiderOfflineRetrievalDeals = true
ConsiderVerifiedStorageDeals = true
ConsiderUnverifiedStorageDeals = true
PieceCidBlocklist = []
ExpectedSealDuration = "24h0m0s"
MaxDealStartDelay = "336h0m0s"
PublishMsgPeriod = "10s"
MaxDealsPerPublishMsg = 8
MaxProviderCollateralMultiplier = 2
SimultaneousTransfersForStorage = 20
SimultaneousTransfersForStoragePerClient = 20
SimultaneousTransfersForRetrieval = 20
Filter = ""
RetrievalFilter = ""
MaxPublishDealsFee = "0 FIL"
MaxMarketBalanceAddFee = "0 FIL"

[API]
  ListenAddress = "/ip4/127.0.0.1/tcp/41235"
  RemoteListenAddress = ""
  Secret = "76c92eae18f2ca6a09dcdd4085604704b853e0cf5a6c96d7dce82bd7aa78cd1b"
  Timeout = "30s"

[Libp2p]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/58418", "/ip6/::/tcp/0"]
  AnnounceAddresses = []
  NoAnnounceAddresses = []
  PrivateKey = "0801124071a7e09c179c4e3e585fb1f57eba66dc728b4d0fa44f1dc880734fc422700eb60d94c77d5c41f3d4c4c85f04e89e4037251621df63cfd778602f2ddcf3a7552e"

[Node]
  Url = "/ip4/192.168.200.4/tcp/3453"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGkiLCJwZXJtIjoiYWRtaW4iLCJleHQiOiIifQ.yqMMxBmIQASoCplBu4UMbU9WD3cqlE7P8U7abJkkUks"

[Messager]
  Url = "/ip4/192.168.200.4/tcp/39812"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGkiLCJwZXJtIjoiYWRtaW4iLCJleHQiOiIifQ.yqMMxBmIQASoCplBu4UMbU9WD3cqlE7P8U7abJkkUks"

[Signer]
  Type = "gateway"
  Url = "/ip4/192.168.200.4/tcp/45132"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGkiLCJwZXJtIjoiYWRtaW4iLCJleHQiOiIifQ.yqMMxBmIQASoCplBu4UMbU9WD3cqlE7P8U7abJkkUks"

[AuthNode]
  Url = "http://192.168.200.4:8989"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGkiLCJwZXJtIjoiYWRtaW4iLCJleHQiOiIifQ.yqMMxBmIQASoCplBu4UMbU9WD3cqlE7P8U7abJkkUks"

[Mysql]
  ConnectionString = ""
  MaxOpenConn = 100
  MaxIdleConn = 100
  ConnMaxLifeTime = "1m"
  Debug = false

[PieceStorage]
  [PieceStorage.Fs]
    Enable = true
    Path = "/Users/lijunlong/piece"
  [PieceStorage.S3]
    Enable = false
    EndPoint = ""
    AccessKey = ""
    SecretKey = ""
    Token = ""

[Journal]
  Path = "journal"

[AddressConfig]
  DisableWorkerFallback = false

[DAGStore]
  RootDir = "/Users/lijunlong/.venusmarket/dagstore"
  MaxConcurrentIndex = 5
  MaxConcurrentReadyFetches = 0
  MaxConcurrencyStorageCalls = 100
  GCInterval = "1m0s"

[RetrievalPaymentAddress]
  Addr = "t3qyjvxdcm6qbqpy54v6x5fkj4hadq5vd4ztyat6ksomwlsdlazkmnlhmgic5ar74jt4764psf5b7mzzioilpq"
  Account = "li"

[RetrievalPricing]
  Strategy = "default"
  [RetrievalPricing.Default]
    VerifiedDealsFreeTransfer = true
  [RetrievalPricing.External]
    Path = ""

```

market-client:

   --node-url value                        必须
   --node-token value                      必须
   --messager-url value                    必须 可选
   --messager-token value                  必须
   --auth-token value                      必须  考虑删除

   --wallet-url value                      钱包地址
   --wallet-token value                    钱包token
   --addr value                            必须

```toml
# Default config:
HomeDir = "~/.marketclient"
SimultaneousTransfersForRetrieval = 20
SimultaneousTransfersForStorage = 20
DefaultMarketAddress = "t3wtmlylzuc7ttbhwppjt7m55p7ywybebdx7kfbwx7ijhthqssptvs746njt22i3xe65zw7hyafutmdoobkcoq"

[API]
  ListenAddress = "/ip4/127.0.0.1/tcp/41231/ws"
  RemoteListenAddress = ""
  Secret = "8ad29ae85d3ecf42442fb4134b635523966d59ee4e60411a515b3c3d2e371b91"
  Timeout = "30s"

[Libp2p]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/34123", "/ip6/::/tcp/0"]
  AnnounceAddresses = []
  NoAnnounceAddresses = []
  PrivateKey = "080112405da357ef86e78ad65d85c37cc440fa6de86739f9074c87544848e16960b69ab9beb3cd2b159e15839446797484c5ddb7f9c603f344c0f2fca0d52e52b81051a1"

[Node]
  Url = "/ip4/192.168.200.4/tcp/3453"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGkiLCJwZXJtIjoic2lnbiIsImV4dCI6IiJ9.QstQiAfP5ahbKYFbm04y5tPOKnIzI7qj9swKriQP1ZA"

[Messager]
  Url = "/ip4/192.168.200.4/tcp/39812"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGkiLCJwZXJtIjoic2lnbiIsImV4dCI6IiJ9.QstQiAfP5ahbKYFbm04y5tPOKnIzI7qj9swKriQP1ZA"

[Signer]
  Type = "wallet"
  Url = "/ip4/127.0.0.1/tcp/5678"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIl19.Y03rbv28jVsXK9t4Ih9a0YmmzGoG2fwa5Ek1VkQByQ0"
```

sealer配置

   --messager-url value         messager url
   --messager-token value       messager token
   --node-url value             node url
   --node-token value           node token
   --gateway-url value          gateway url
   --gateway-token value        gateway token
   --auth-token value           auth token

   --market-mode solo           indicate the deployment method of the venus-market, one of solo, `pool`, Default: `solo` (default: "solo")
   --market-url value           market url
   --market-token value         market token

   --piecestorage value         config storage for piece  (eg  fs:/mnt/piece   s3:{access key}:{secret key}:{option token}@{region}host/{bucket}

sealer 配置

```toml
[Node]
  Url = "/ip4/192.168.200.19/tcp/3453"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiMjAwLTIyIiwicGVybSI6InNpZ24iLCJleHQiOiIifQ.cgLr0QHbUPq7djU4SqoEbMJQIL8bwqbkCP11n4uWNoQ"

[Messager]
  Url = "/ip4/192.168.200.19/tcp/39812"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiMjAwLTIyIiwicGVybSI6InNpZ24iLCJleHQiOiIifQ.cgLr0QHbUPq7djU4SqoEbMJQIL8bwqbkCP11n4uWNoQ"


[PieceStorage]
  [PieceStorage.Fs]
    Enable = false
    Path = ""
  [PieceStorage.S3]
    Enable = false
    EndPoint = ""
    AccessKey = ""
    SecretKey = ""
    Token = ""

[MarketNode]
  Url = "/ip4/192.168.200.19/tcp/xxxx"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiMjAwLTIyIiwicGVybSI6InNpZ24iLCJleHQiOiIifQ.cgLr0QHbUPq7djU4SqoEbMJQIL8bwqbkCP11n4uWNoQ"

[RegisterProof]
  Urls = ["/ip4/192.168.200.19/tcp/45132"]
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiMjAwLTIyIiwicGVybSI6InNpZ24iLCJleHQiOiIifQ.cgLr0QHbUPq7djU4SqoEbMJQIL8bwqbkCP11n4uWNoQ"

//此处在连接pool里面的gateway时，配置和上面保持一致， 在连接自己部署的market是在单独配置自己的market url和token，这时候会和marketNode保持一致
[RegisterMarket]
  Urls = ["/ip4/192.168.200.19/tcp/xxxx"]
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiMjAwLTIyIiwicGVybSI6InNpZ24iLCJleHQiOiIifQ.cgLr0QHbUPq7djU4SqoEbMJQIL8bwqbkCP11n4uWNoQ"

```

# market中发送地址和用户关系

在messager设计中，发送消息的地址需要知晓关联的账号。这样messager中进行消息签名时，可以通过账号，查找对应的钱包，在进行签名。

因此当market给messager发消息时，需要建立发送地址和账号的关系，然而设置market发送消息的地址可能是owner/worker/control， 这些地址和账号的关系在系统中是不存在的。
甚至检索地址不是个矿工地址，改地址在系统中和账号之间也不具备关联关系，这里可能需要一定改变来简化逻辑。

## 目前的做法
因为知道矿工地址的账号，然后把矿工下面的所有地址都关联到矿工账号上面。
对于直接配置的检索地址，直接配置检索地址对应的用户

## 简化思路

局部改变：是否可以提供一个admin接口，在这个接口中，直接查找是否存在支持这个地址的账号（在gateway上查找），然后使用这个账号，钱包进行签名。

整体改变：gateway不关联账号，仅关联钱包， 只要查找到对应的钱包就行，这样messager收到消息查找是否存在对应的地址，存在则记录记录消息，发送这不在需要制定是属于那个账号发送的消息。
        1. 好处 WalletSign接口兼容
        2. 发送消息变得简单
        3. 考虑是否存在安全风险
