### DISCUSSION TITLE
[设计] SP独立市场配置功能设计讨论

### DISCUSSION THREAD

**Discussion by Fatman13** [filecoin-project/venus#5425] [Ideas]
来自 @diwufeiwen 的设计

# 市场属性配置

## Simple Summary (概述)

矿工可以自己配置存储市场和检索市场的属性。

## Abstract (功能简介)

`venus-market` 支持矿工的市场交易属性可独立配置，并可以由矿工自己配置，而不是通过链服务维护人员间接进行。

`venus-market` 推荐作为独立组件部署，将 `solo-run` 模式作为默认启动方式。（为什么这样做后文会详细讨论）

关联：
- [ ] 提案的[issue](https://github.com/filecoin-project/venus/issues/5410)

## Motivation (来源/背景)

`Filecoin` 网络中的矿工参与市场交易需要一些属性来保证交易过程正常进行，也可以通过一些属性来设置自己的交易取向，如：仅接受可验证订单、只进行离线订单等。目前的可配置属性如下：

```toml
# Default config:
ConsiderOnlineStorageDeals = true
ConsiderOfflineStorageDeals = true
ConsiderOnlineRetrievalDeals = true
ConsiderOfflineRetrievalDeals = true
ConsiderVerifiedStorageDeals = true
ConsiderUnverifiedStorageDeals = true
PieceCidBlocklist = []
ExpectedSealDuration = "24h0m0s"
MaxDealStartDelay = "336h0m0s"
PublishMsgPeriod = "30s"
MaxDealsPerPublishMsg = 8
MaxProviderCollateralMultiplier = 2
SimultaneousTransfersForStorage = 20
SimultaneousTransfersForStoragePerClient = 20
SimultaneousTransfersForRetrieval = 20
Filter = ""
RetrievalFilter = ""
TransfePath = ""
MaxPublishDealsFee = "0 FIL"
MaxMarketBalanceAddFee = "0 FIL"
```

在目前的 `venus-market` 实现中，所有的矿工共用一份配置，无法单独为某个矿工配置交易属性。

`venus-market` `pool-run` 模式下，矿工无法对交易属性进行直接管理：查询和配置。

`venus-market` `pool-run` 模式下，`pieces`数据在目前的协议下无法直接存储到`SP`的封装机器，在封装过程中需要下载，当订单量较大时，对网络带宽的要求较高，故推荐将`venus-market`作为独立组件部署。
后续协议(boost?待考察)支持订单交易中可以将数据直接存到`SP`封装机器上时优先推荐作为链服务组件?

### 默认的部署方式

将 `solo-run` 模式作为默认的启动方式。主要是为了减少不必要的数据传输，原因见上文。

### 属性配置

- 有一套全局的属性表，当矿工没有独立配置时采用全局配置；
- 矿工有独立的属性表。

### 用户界面

- `pool-run` 模式下，通过 `venus-sector-manager` 提供的命令进行配置；
- `solo-run` 模式下，通过 `venus-market` 提供的命令修改配置文件（`config.toml`）进行配置；

## Backwards Compatibility（兼容性）

不存在兼容问题，将原本的配置作为全局配置，矿工未配置独立的属性时采用全局属性。
