### ISSUE TITLE
[venus] boot节点少的情况下，某些情况无法启动同步

### ISSUE THREAD

**Issue by LinZexiao** [filecoin-project/venus#5076]
在使用forcenet的测试环境中，发现在有peer连接的情况下，依旧无法完成链同步，报错信息为  no peers available

```
root@tanlang ~/t/venus ((v1.6.0))# ./venus swarm peers
{
        "Peers": [
                {
                        "Addr": "/ip4/192.168.200.128/tcp/56300",
                        "Peer": "QmdMet1bEsvwbopUvZLRBYiPkpv2CZs3NRmpdg16yH1QB7",
                        "Latency": "",
                        "Muxer": "",
                        "Streams": null
                }
        ]
}
```

```
root@tanlang ~/t/venus ((v1.6.0))# ./venus sync history
History:
SyncTarget: 1
        Base: 20096 { bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga }
        Target: 20156 { bafy2bzaced4wfnbfjv7jp7i4hkv2sclnrrtsvtxsfy7zy2t3usvkimiu3mj6g }
        Current:
        Time: 0
        Status: error
        Err: no peers available

SyncTarget: 2
        Base: 20096 { bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga }
        Target: 20158 { bafy2bzacedi3lss26dqzhmmxhsn7q6pqzlyhelbh3yzec3jrhsxf5rffy5ug6 }
        Current:
        Time: 0
        Status: error
        Err: no peers available

SyncTarget: 3
        Base: 20096 { bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga }
        Target: 20159 { bafy2bzacedsablobprvodwievxqskk5gszfrrzweufbwdjsem5shc3uvchbxw }
        Current:
        Time: 0
        Status: error
        Err: no peers available

SyncTarget: 4
        Base: 20096 { bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga }
        Target: 20161 { bafy2bzacecirqplc6otcbnb5h2b7vap6cocklvw5zeh4uxjwjf6og7cnsxzhi }
        Current:
        Time: 0
        Status: error
        Err: no peers available

SyncTarget: 5
        Base: 20096 { bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga }
        Target: 20162 { bafy2bzacedx5fsrrbmwk7lpuc6yh5ujoefe3croun6euwg67lyr73rxaq2izg }
        Current:
        Time: 0
        Status: error
        Err: no peers available

SyncTarget: 6
        Base: 20096 { bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga }
        Target: 20163 { bafy2bzaceagtbxrzyjic7jaxokt4yops4g6wfmofid7mtp5gcruwffeurkmu2 }
        Current:
        Time: 0
        Status: error
        Err: no peers available

SyncTarget: 7
        Base: 20096 { bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga }
        Target: 20164 { bafy2bzacedoerqeq76ktvfj4d2pplqsgeyjqs5rrmk7nbupbfoftozwvgry2m }
        Current:
        Time: 0
        Status: error
        Err: no peers available

SyncTarget: 8
        Base: 20096 { bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga }
        Target: 20165 { bafy2bzaceaujnc5awat74kbmanuo4hbnml6utouvnffd5jfip6ys65c3yw6h4 }
        Current:
        Time: 0
        Status: error
        Err: no peers available

SyncTarget: 9
        Base: 20096 { bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga }
        Target: 20166 { bafy2bzacebm2eavxyzew6rwsovpa36urgq2x5drms67u634jyzhsfsej4l6bk }
        Current:
        Time: 0
        Status: error
        Err: no peers available

SyncTarget: 10
        Base: 20096 { bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga }
        Target: 20172 { bafy2bzacecgxe3tji3f2vefkmbgqxptkmmt7q26riw2e2afjdylouy3ku4u5c }
        Current:
        Time: 0
        Status: error
        Err: no peers available

SyncTarget: 11
        Base: 20096 { bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga }
        Target: 20173 { bafy2bzaced6unqg3ivhberddmygzmi4hy6oi36jkqecudsegpjtkax7h2jg7s }
        Current:
        Time: 0
        Status: error
        Err: no peers available

root@tanlang ~/t/venus ((v1.6.0))# ./venus chain head
{
        "Height": 20096,
        "ParentWeight": "211616615",
        "Cids": [
                {
                        "/": "bafy2bzacectuzfmrvgm562qe6tgle4mfxijes2c4tonccdalholsz5m3ni5ga"
                }
        ],
        "Timestamp": "2022-07-13 15:22:45"
}
```
