### ISSUE TITLE
[collab] Integration test with CIDgravity / 尝试与CIDgravity集成

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5669]
## 背景

继Venus完成集成[deal filter](https://github.com/filecoin-project/venus/issues/5565)之后，尝试与CIDgravity进行集成。

## CIDgravity集成测试

1. 首先登陆CIDgravity[官网](https://app.cidgravity.com/)，使用github授权登陆方式创建账号。
2. 用worker地址签名，来claim自己的miner_id。
3. 在setting中获取API token。
4. 节点本地安装CIDgravity[连接器](https://github.com/CIDgravity/CIDgravity-X)，并配置API token。

## 所需资源

- 主网节点测试（暂时没有测试网支持）
- 社区运维

**Comment by Fatman13** [comment]
![image](https://user-images.githubusercontent.com/1591330/218353459-c59bd53e-23a4-45e4-8495-f692e0d78a32.png)

**Comment by Fatman13** [comment]
```toml
# Default config:
SimultaneousTransfersForStorage = 20
SimultaneousTransfersForStoragePerClient = 20
SimultaneousTransfersForRetrieval = 20

[API]
  ListenAddress = "/ip4/127.0.0.1/tcp/41235"
  RemoteListenAddress = ""
  Timeout = "30s"
  PrivateKey = "32b40d9518f3e89d11fc62c590b4e7ea39da04a99489da94d19efa802a2c24c7"

[Libp2p]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/58418", "/ip6/::/tcp/0"]
  AnnounceAddresses = []
  NoAnnounceAddresses = []
  PrivateKey = "08011240d1e7d23010175ec10e4a55e00b1c9cdc4653bdbf7f78f9659b514dbae15643a0a417900a0051a5a1e7d1f96dea439140c1bbadfa49e58a55956dd3253798020a"

[Node]
  Url = "/ip4/127.0.0.1/tcp/3453"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJwZXJtIjoiYWRtaW4iLCJleHQiOiIifQ.ei825Nj4pQUuq0qyoBR593my8BAK0K_troWgfnZKrU0"

[Messager]
  Url = "/ip4/127.0.0.1/tcp/39812/"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJwZXJtIjoiYWRtaW4iLCJleHQiOiIifQ.ei825Nj4pQUuq0qyoBR593my8BAK0K_troWgfnZKrU0"

[Signer]
  Type = "gateway"
  Url = "/ip4/127.0.0.1/tcp/45132/"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJwZXJtIjoiYWRtaW4iLCJleHQiOiIifQ.ei825Nj4pQUuq0qyoBR593my8BAK0K_troWgfnZKrU0"

[AuthNode]
  Url = "http://127.0.0.1:8989"
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJwZXJtIjoiYWRtaW4iLCJleHQiOiIifQ.ei825Nj4pQUuq0qyoBR593my8BAK0K_troWgfnZKrU0"

[Mysql]
  ConnectionString = ""
  MaxOpenConn = 100
  MaxIdleConn = 100
  ConnMaxLifeTime = "1m"
  Debug = false

[PieceStorage]

  [[PieceStorage.Fs]]
    Name = "DefaultPieceStorage"
    ReadOnly = false
    Path = "/data/piece-storage"

[DAGStore]
  RootDir = "/root/.venusmarket/dagstore"
  MaxConcurrentIndex = 5
  MaxConcurrentReadyFetches = 0
  MaxConcurrencyStorageCalls = 100
  GCInterval = "1m0s"
  Transient = ""
  Index = ""
  UseTransient = false

[CommonProvider]
  ConsiderOnlineStorageDeals = true
  ConsiderOfflineStorageDeals = true
  ConsiderOnlineRetrievalDeals = true
  ConsiderOfflineRetrievalDeals = true
  ConsiderVerifiedStorageDeals = true
  ConsiderUnverifiedStorageDeals = true
  PieceCidBlocklist = []
  ExpectedSealDuration = "24h0m0s"
  MaxDealStartDelay = "336h0m0s"
  PublishMsgPeriod = "1h0m0s"
  MaxDealsPerPublishMsg = 8
  MaxProviderCollateralMultiplier = 2
  Filter = ""
  RetrievalFilter = ""
  TransferPath = ""
  MaxPublishDealsFee = "0 FIL"
  MaxMarketBalanceAddFee = "0 FIL"
  RetrievalPaymentAddress = ""
  [CommonProvider.RetrievalPricing]
    Strategy = "default"
    [CommonProvider.RetrievalPricing.Default]
      VerifiedDealsFreeTransfer = true
    [CommonProvider.RetrievalPricing.External]
      Path = ""
  Filter = "echo filter"

[Journal]
  Path = "journal"

[Metrics]
  Enabled = false
  [Metrics.Exporter]
    Type = "prometheus"
    [Metrics.Exporter.Prometheus]
      RegistryType = "define"
      Namespace = ""
      EndPoint = "/ip4/0.0.0.0/tcp/4568"
      Path = "/debug/metrics"
      ReportingPeriod = "10s"
    [Metrics.Exporter.Graphite]
      Namespace = ""
      Host = "127.0.0.1"
      Port = 4568
      ReportingPeriod = "10s"

[[Miners]]
  Addr = "f01005"
  Account = "admin"
  Filter = "echo filter"
  ConsiderOnlineStorageDeals = true
  ConsiderOfflineStorageDeals = true
  ConsiderOnlineRetrievalDeals = true
  ConsiderOfflineRetrievalDeals = true
  ConsiderVerifiedStorageDeals = true
  ConsiderUnverifiedStorageDeals = true
  PieceCidBlocklist = []
  ExpectedSealDuration = "24h0m0s"
  MaxDealStartDelay = "336h0m0s"
  PublishMsgPeriod = "1h0m0s"
  MaxDealsPerPublishMsg = 8
  RetrievalFilter = ""
  TransferPath = ""
  [Miners.RetrievalPricing]
    Strategy = "default"
    [Miners.RetrievalPricing.Default]
      VerifiedDealsFreeTransfer = true
    [Miners.RetrievalPricing.External]
      Path = ""
  MaxPublishDealsFee = "0 FIL"
  MaxMarketBalanceAddFee = "0 FIL"
  RetrievalPaymentAddress = ""
```
